---
title: "space_scratchbook"
output: html_document
---

```{r}
library(tidyverse)
library(tidytuesdayR)
library(plotly)
library(Cairo)
library(scales)
library(rayshader)
library(extrafont)
```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-07-14')
tuesdata <- tidytuesdayR::tt_load(2020, week = 29)

astronauts <- tuesdata$astronauts

```
```{r}
#font_import()
astronauts
```

```{r}
loadfonts(device = "win")
```

```{r}
astronauts %>% 
  group_by(nationality) %>% 
  summarise(n=n()) %>% 
  arrange(desc(n))
```
```{r fig.height=18, fig.width=12}
p1 <- astronauts %>% 
  mutate(
    country = case_when(
      !nationality %in% c("U.S.", "U.S.S.R/Russia") ~ "Other",
      nationality == "U.S." ~ "USA",
      nationality == "U.S.S.R/Russia" ~ "Russia/USSR"
    )
  ) %>% 
  ggplot(
    aes(
      x = year_of_mission,
      fill = country,
      color = country
    )
  )+
  geom_dotplot(binaxis = "x",
               position = "identity",
               stackgroups=T, 
               binpositions="all",
               dotsize = .7,
               method = "histodot",
               binwidth = 1,
               stackratio = 1.3,
               stackdir = "center"
  )+
  coord_flip()+
  theme_minimal()+
  
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  
  labs(
    title = "IN ORBIT",
    subtitle = "Astronauts in Earth orbit, by year of mission and country. (Each row of dots is one year)\nData from Mariya Stavnqichuk and Tatsuya Corlett. | Visualized by Robert Bui
    \n \n",
    x = "",
    y = "\n",
    fill = " \n"
  )+
  
  scale_y_continuous(breaks = pretty_breaks(n=1))+
  scale_x_continuous(breaks = pretty_breaks(n=5), limits = c(1945,2025))+
  
  theme(
    
    plot.margin=unit(c(6,6,6,6),"cm"),
    plot.background = element_rect(fill = '#030a16'),
    plot.title = element_text(
      hjust = 0.5,
      face = "bold",
      size = 96, 
      family = "Onyx", 
      color = "#ffffff"
    ),
    plot.subtitle = element_text(
      hjust = 0.5,
      face = "italic",
      size = 18, 
      family = "Segoe UI Semilight", 
      color = "#ffffff"
    ),
    
    text = element_text(size = 10, family = "Segoe UI Semilight", color = "#ffffff"),
    
    axis.text.y = element_text(size = 8, color="#ffffff"),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 12, color="#ffffff", face="bold"),

    
    panel.grid.major.x = element_line(linetype = "dotted" , colour="#3A506B"),
    panel.grid.major.y = element_line(linetype = "dotted" , colour="#3A506B", size = .05),

    panel.grid.minor = element_blank(),
    
    strip.text = element_text(size = 14,face="bold", color="#ffffff"),
    
    legend.position = "bottom",
    legend.title = element_text(size = 16, color="#ffffff"),
    legend.text = element_text(size = 18, color="#ffffff")
  )+
  guides(
    color = FALSE,
    fill = guide_legend(reverse=T)
  )

p1
```

```{r}
ggsave(p1, 
       units = c("in"),
       width = 12,
       height = 16,
       dpi = 300, 
       file="outplot1.png", 
       type="cairo-png")
```

