---
title: "coffee_scratch"
output: html_document
---

```{r}
library(tidyverse)
library(tidytuesdayR)
library(plotly)
library(fmsb)
library(BBmisc)
library(Cairo)
```

```{r}
windowsFonts()
```


```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 28)
coffee_ratings <- tuesdata$coffee_ratings

```
```{r}
# coord_rader config credit to Erwan Le Pennec, l'École polytechnique
coord_radar <- function (theta = "x", start = 0, direction = 1) 
{
 theta <- match.arg(theta, c("x", "y"))
 r <- if (theta == "x") 
        "y"
      else "x"
 ggproto("CoordRadar", CoordPolar, theta = theta, r = r, start = start, 
      direction = sign(direction),
      is_linear = function(coord) TRUE)
}
```

```{r}
coffee_ratings$country_of_origin[coffee_ratings$country_of_origin == "United States (Puerto Rico)"] <- 'United States'
coffee_ratings$country_of_origin[coffee_ratings$country_of_origin == "United States (Hawaii)"] <- 'United States'
coffee_ratings$country_of_origin[coffee_ratings$country_of_origin == "Tanzania, United Republic Of"] <- 'Tanzania'
coffee_ratings$country_of_origin[coffee_ratings$country_of_origin == "Cote d?Ivoire"] <- 'Cote d\'Ivoire'

countries <- coffee_ratings %>% 
  group_by(country_of_origin) %>% 
  summarize(n=n()) %>% 
  arrange(desc(n)) %>% 
  filter(
    n >= 10
  ) %>% 
  select(country_of_origin)

plotdata <- coffee_ratings %>% 
  group_by(country_of_origin) %>% 
  summarize(
    `Aroma` = mean(aroma),
    `Flavour` = mean(flavor),
    `Aftertaste` = mean(`aftertaste`),
    `Acidity` = mean(`acidity`),
    `Body` = mean(`body`),
    `Balance` = mean(balance),
    `Uniformity` = mean(uniformity),
    `Clean Cup` = mean(clean_cup),
    Sweetness = mean(sweetness),
    `Cupper Points` = mean(cupper_points),
    Moisture = mean(moisture)
  ) %>% 
  right_join(countries) %>% 
  mutate(
    `AROMA` = scale(Aroma),
    `FLAVOUR` = scale(Flavour),
    `AFTERTASTE` = scale(`Aftertaste`),
    `ACIDITY` = scale(`Acidity`),
    `BODY` = scale(`Body`),
    `BALANCE` = scale(Balance),
    `UNIFORMITY` = scale(Uniformity),
    `CLEAN CUP` = scale(`Clean Cup`),
    SWEETNESS = scale(Sweetness),
    `CUPPER POINTS` = scale(`Cupper Points`),
    MOISTURE = scale(Moisture)
  ) %>% 
  select(
    country_of_origin, AROMA, FLAVOUR, AFTERTASTE, ACIDITY, BODY, BALANCE, UNIFORMITY, `CLEAN CUP`, SWEETNESS, `CUPPER POINTS`, MOISTURE
  ) %>% 
  pivot_longer(
    cols = -country_of_origin,
    names_to = "index",
    values_to = "value"
  ) %>% 
  mutate(
    country_of_origin = toupper(country_of_origin)
  )
```


```{r fig.width=18, fig.height= 17}
p <- plotdata %>% 
  ggplot(
    aes(
      x = index,
      y = value,
      color = index,
      group = country_of_origin
    )
  )+
  
  geom_point(size = 4)+
  #geom_point(shape =21, fill = NA, size = 4)+
  
  geom_segment(
    aes(
      x = index,
      xend = index, yend = 0, 
      y = value,
      color = index,
      fill = index
    ),
    size = .85,
    alpha=.65
  )+

  #coord_polar(clip = "off")+
  coord_flip()+
  
  lims()+
  
  
  facet_wrap(
    ~paste("\n",country_of_origin, "\n \n"),
    strip.position = "left",
    switch = "x"
  )+  
  scale_fill_viridis_d()+
  theme_minimal()+
  
  labs(
    title = "Coffee Around the World",
    subtitle = "Taste profile of coffee from around the world based on deviation from mean taster scores, grouped by Country of origin. \n Score has been normalized to a mean of 0 and standard deviation of 1. \n Outward is better score, while inward is worse. \n \n",
    x = "Score Component",
    y = "Deviation from Mean Score (each dotted line is 1 SD)\n"
  )+
  
  theme(
    
    plot.margin=unit(c(1,1,1,1),"cm"),
    plot.background = element_rect(fill = '#0B132B'),
    plot.title = element_text(
      hjust = 0.5,
      face = "bold",
      size = 24, 
      family = "Arial", 
      color = "#ffffff"
    ),
    plot.subtitle = element_text(
      hjust = 0.5,
      face = "italic",
      size = 12, 
      family = "Arial", 
      color = "#ffffff"
    ),
    
    text = element_text(size = 10, family = "Arial", color = "#ffffff"),
    
    axis.text.y = element_text(size = 8, color="#ffffff"),
    axis.text.x = element_text(size = 6, color="#ffffff"),
    axis.title.x = element_text(size = 12, color="#ffffff", face="bold"),
    axis.title.y = element_text(size = 12, color="#ffffff", face="bold"),

    
    panel.grid.major.x = element_line(linetype = "dotted" , colour="#3A506B"),
    panel.grid.major.y = element_blank(),

    panel.grid.minor = element_blank(),
    
    strip.text = element_text(size = 14,face="bold", color="#ffffff"),
    
    legend.position = "none",
    legend.title = element_blank(),
    legend.text = element_blank()
  )

p
```

```{r}
ggsave(p, 
       units = c("in"),
       width = 18,
       height = 17,
       dpi = 300, 
       file="outplot1.png", 
       type="cairo-png")
```

